apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planner-lbl
  template:
    metadata:
      labels:
        app: planner-lbl
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-prod
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env-prod
        - name: planner-container
          image: husseinatdocker/planner-app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: planner-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32000
  selector:
    app: planner-lbl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: planner-lbl
  name: planner-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planner-lbl
  name: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planner-lbl
  template:
    metadata:
      labels:
        app: planner-lbl
    spec:
      containers:
        - image: mongo
          name: database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: planner-lbl
  name: mongo-database-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 27017
      nodePort: 33000
  selector:
    app: planner-lbl
